//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace EasyMemo.Domain.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class Account : AggregateRoot
	{
		public virtual string Name
		{
			get;
			set;
		}

		public virtual string Password
		{
			get;
			set;
		}

		public virtual string Email
		{
			get;
			set;
		}

		public virtual string DisplayName
		{
			get;
			set;
		}

		public virtual DateTime DateCreated
		{
			get;
			set;
		}

		public virtual Nullable<DateTime> DateLastLogon
		{
			get;
			set;
		}

		public virtual List<Role> Roles
		{
			get;
			set;
		}

		public virtual List<Memo> Memos
		{
			get;
			set;
		}

	}
}

