//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace EasyMemo.Domain.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class Account : AggregateRoot
	{
		public virtual string Name
		{
			get;
			set;
		}

		public virtual string Password
		{
			get;
			set;
		}

		public virtual string Email
		{
			get;
			set;
		}

		public virtual string DisplayName
		{
			get;
			set;
		}

		public virtual DateTime DateCreated
		{
			get;
			set;
		}

		public virtual Nullable<DateTime> DateLastLogon
		{
			get;
			set;
		}

		public virtual List<Role> Roles
		{
			get;
			set;
		}

	}
}

