//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace EasyMemo.Domain.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract partial class AggregateRoot : Apworks.IAggregateRoot
	{
		public virtual Guid ID
		{
			get;
			set;
		}

		public virtual Nullable<bool> IsDeleted
		{
			get;
			set;
		}

	}
}

