//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace EasyMemo.Domain.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	[FlagsAttribute]
	public enum Privilege : int
	{
		SystemAdministration = 16777215,
		Ignore = 0,
		ManageAccounts = 1,
		SystemDelegation = 3,
		ManageRoles = 2,
	}
}
